theme: jekyll-theme-minimal
title: Kristina Maceković - Personal Site
description: Here you can learn a bit about me, my interests and experience(s).
logo: [Location of the logo]
show_downloads: "false"
google_analytics: UA-129657260-1
